# Change these first
owner: radquincy # Your GitHub organization or username, where this repository lives
repo: radquincy-upptime # The name of this repository

sites:
  - name: RadQuincy.com
    url: https://radquincy.com/
  - name: RadGames
    url: https://radgames.radquincy.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /radquincy-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Rad Upptime
  introTitle: "**Upptime** keeping my projects together"
  introMessage: Check out [**Upptime**](https://github.com/upptime/upptime) as its a supper powerful tool, able to help power these rad websites.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
